config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    resources :pins do
        member do
            put "like", to: "pins#upvote"
        end
    end
    root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").page(params[:page]).per(20)
  end

  def show
  end

  def edit
    return not_authorized unless current_user == @pin.user
  end

  def destroy
    return not_authorized unless current_user == @pin.user
    @pin.destroy
    redirect_to root_path, notice: "Pin destroyed"
  end

  def update
    return not_authorized unless current_user == @pin.user
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin updated"
    else
      render 'edit'
    end
  end

  def upvote
    @pin.upvote_by(current_user)
    redirect_to :back
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: "Sucessfully created pin"
    else
      render 'new'
    end

  end

  def new
    @pin = current_user.pins.build
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def not_authorized
    redirect_to pins_path, notice: "Denied"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinterestClone</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class ="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand">
            <%= link_to "Pin Board", root_path %>
          </div>
        </div>

        <ul class="nav navbar-nav navbar-right navbar-collapse collapse">
          <% if user_signed_in? %>
            <li> <%= link_to 'New pin', new_pin_path%></li>
            <li> <%= link_to 'Account', edit_user_registration_path%></li>
            <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%></li>
          <% else %>
            <li> <%= link_to 'Sign up', new_user_registration_path %></li>
            <li> <%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pins/_form.html.erb
  <%= simple_form_for(@pin, html: { multipart: true}) do |form| %>

    <% if @pin.errors.any? %>

    	<h2 id="errors"> <%= pluralize(@pin.errors.count, "error") %>
    	prevented this pin from saving </h2>

    	<ul>
    	<%= @pin.errors.full_messages.each do |msg| %>

    		<li><%= msg %></li>
    	<% end %>
    	</ul>
    <% end %>

<div class="form-group">
    <%= form.input :image, input_html: {class: 'form-control'}%>
</div>

<div class="form-group">
    <%= form.input :title, input_html: {class: 'form-control'}%>
</div>

<div class="form-group">
    <%= form.input :description, input_html: {class: 'form-control'}%>
</div>

    <%= form.button :submit, class: "btn btn-primary"%> 

<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1> Edit Pin </h1>
      </div>
      <div class="panel-body">
        <strong class="center">Current Image</strong>
        <br/>
        <%= image_tag @pin.image.url(:medium) %>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do | pin | %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.image.url), pin %>
      <div class="panel-body">
        <h2> <%= link_to pin.title, pin %> </h2>
        <p class="user">Submitted by <%= pin.user.email %></p>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @pins %>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1> New Pin </h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div id ="pin_show" class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url() %>
      </div> <!-- panel-heading -->
      <div class="panel-body">
        <%= content_tag :h1, @pin.title %>
        <%= content_tag :p, @pin.description, class: 'description' %>
        <p> Submitted by <%= @pin.user.email %> </p>
      </div> <!-- panel-body -->
      <div class ="panel-footer">
        <div class="row">
          <div class ="col-md-6">
            <p class="user"> Submitted by <%= @pin.user.email %> </p>
          </div>
          <div class="col-md-6">
          <div class ="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart"><%= @pin.get_upvotes.size%></span>
              <%end %>
              <% if user_signed_in?  and @pin.user == current_user%>
                <%= link_to 'Edit', edit_pin_path, class: 'btn btn-default' %>
                <%= link_to 'Delete', pin_path, method: 'delete', data: {confirm: "You sure?"}, class: 'btn btn-default' %>
              <% end %>
            </div><!-- btn-group -->
          </div><!-- col-md-6 -->
        </div><!-- row -->
      </div><!-- panel-footer -->
    </div><!-- panel panel-default-->
  </div><!-- col-md-8-->
</div><!-- #pin_show -->